services:
  - type: web
    name: full-stack-login
    env: node
    plan: free
    buildCommand: cd backend && npm install && npm run build && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
