services:
  - type: web
    name: full-stack-login
    env: node
    plan: free
    buildCommand: cd frontend && npm install && npm run build && cd ../backend && npm install && node scripts/copyBuild.js
    startCommand: node backend/server.js
    envVars:
      - key: NODE_ENV
        value: production
