services:
  - type: web
    name: full-stack-login
    env: node
    plan: free
    buildCommand: npm install --prefix frontend && npm run build --prefix frontend && mkdir -p backend/build && cp -r frontend/build/* backend/build/
    startCommand: npm start --prefix backend
    envVars:
      - key: NODE_ENV
        value: production
